"""
Стартовые knowledge packs v1 — ~40 записей на агента.
Масштабирование до GB: scripts/ingest_knowledge_packs.py + внешние JSONL/Markdown.
"""

from __future__ import annotations


def _e(title: str, content: str, topic: str = "", keywords: list | None = None) -> dict:
    return {
        "title": title,
        "topic": topic or title,
        "content": content,
        "keywords": keywords or [],
        "source": "pack:v1",
    }


def _expand(base: list[tuple]) -> list[dict]:
    return [_e(t, c, tp, kw) for t, c, tp, kw in base]


# ─── PM ───────────────────────────────────────────────────────────────
PM = _expand([
    ("Scrum Guide 2020", "Спринт 1–4 нед. Три роли: PO, SM, Dev Team. Артефакты: Product Backlog, Sprint Backlog, Increment. События: Sprint Planning, Daily Scrum ≤15 мин, Review, Retro. Definition of Done обязателен для каждого item.", "Agile", ["scrum", "sprint", "agile"]),
    ("Kanban метод", "WIP limits на колонках. Pull-система вместо push. Метрики: cycle time, throughput, CFD. Классы обслуживания: expedite, fixed date, standard, intangible. Эволюционное изменение без революций.", "Kanban", ["kanban", "wip", "flow"]),
    ("OKR framework", "Objective — качественная цель. Key Results — 2–5 измеримых KR на квартал. Оценка 0.0–1.0; 0.7 считается успехом. Каскад: company → team → individual. Не привязывать OKR к бонусам напрямую.", "OKR", ["okr", "goals", "metrics"]),
    ("DORA metrics", "Four Keys: Deployment Frequency, Lead Time for Changes, Change Failure Rate, MTTR. Elite vs Low performers по годовым бенчмаркам Google. Использовать для диалога с инженерами, не для наказаний.", "DORA", ["dora", "devops", "metrics"]),
    ("User Story Mapping", "Backbone = user journey слева направо. Stories под backbone. Walking skeleton — минимальный end-to-end slice. Релизные slices горизонтально. Jeff Patton: shared understanding важнее backlog.", "Planning", ["story", "mapping", "backlog"]),
    ("RICE prioritization", "Score = (Reach × Impact × Confidence) / Effort. Reach — users/quarter. Impact: 3=massive, 2=high, 1=medium, 0.5=low. Confidence 0–100%. Сравнивать относительно, не абсолют.", "Prioritization", ["rice", "priority"]),
    ("MoSCoW", "Must / Should / Could / Won't this time. Must ≤60% capacity. Явно фиксировать Won't чтобы управлять ожиданиями стейкholders.", "Prioritization", ["moscow", "scope"]),
    ("Stakeholder mapping", "Power/Interest grid: Manage closely, Keep satisfied, Keep informed, Monitor. RACI для решений. Коммуникационный план по частоте и каналу.", "Communication", ["stakeholder", "raci"]),
    ("Risk register", "Probability × Impact matrix. Mitigate, transfer, accept, avoid. Owner на каждый риск. Review на каждом sprint planning.", "Risk", ["risk", "mitigation"]),
    ("Sprint planning", "Capacity = velocity × focus factor. Sprint goal одним предложением. Tasks ≤1 day. DoD checklist на board. Не overcommit >85% capacity.", "Sprint", ["planning", "velocity"]),
    ("Daily standup", "Три вопроса: вчера, сегодня, блокеры. SM фасилитирует, не status для менеджера. Блокеры — action после standup ≤24h.", "Scrum", ["standup", "daily"]),
    ("Sprint review", "Demo working software, не slides. Stakeholders feedback → backlog. Celebrate wins. 1h per week sprint length rule of thumb.", "Scrum", ["review", "demo"]),
    ("Retrospective", "Start/Stop/Continue или 4Ls. Psychological safety. ≤3 action items с owner. Follow up previous retro actions first.", "Scrum", ["retro", "improvement"]),
    ("Velocity tracking", "Story points per sprint, rolling average 3–6 sprints. Не сравнивать команды. Trend важнее абсолютного числа.", "Metrics", ["velocity", "forecast"]),
    ("Roadmap types", "Now/Next/Later (no dates) vs timeline roadmap. Outcome-based roadmap vs feature list. Theme → epic → story hierarchy.", "Roadmap", ["roadmap", "product"]),
    ("INVEST criteria", "Independent, Negotiable, Valuable, Estimable, Small, Testable user stories. Split по workflow steps, CRUD, rules variations.", "Stories", ["invest", "user story"]),
    ("Epic breakdown", "Epic → features → stories → tasks. Vertical slicing предпочтительнее horizontal. Spikes timeboxed с deliverable: decision doc.", "Backlog", ["epic", "decomposition"]),
    ("PI Planning SAFe", "Program Increment 8–12 weeks. Teams commit to PI objectives. ROAM risks: Resolved, Owned, Accepted, Mitigated. ART sync.", "SAFe", ["safe", "pi planning"]),
    ("Lean Startup", "Build-Measure-Learn loop. MVP минимальный для validated learning. Pivot vs persevere decision. Innovation accounting.", "Product", ["lean", "mvp"]),
    ("Jobs To Be Done", "Customer hires product to get job done. Functional, emotional, social jobs. Outcome-driven innovation over demographics.", "Product", ["jtbd", "discovery"]),
    ("Kano model", "Basic, Performance, Delight features. Delighters decay to performance over time. Survey paired questions.", "Product", ["kano", "features"]),
    ("Team topologies", "Stream-aligned, platform, enabling, complicated-subsystem teams. Cognitive load as constraint. Thinnest viable platform.", "Org", ["team", "topology"]),
    ("Escalation path", "Blocker >24h → SM → PO → sponsor. Definition of escalation triggers. No silent suffering.", "Process", ["escalation", "blocker"]),
    ("Release planning", "Release train vs continuous delivery. Feature flags для partial release. Rollback plan mandatory for prod.", "Release", ["release", "deploy"]),
    ("Capacity planning", "Holidays, meetings tax ~20%, onboarding discount. Focus factor 0.6–0.8 for new teams.", "Planning", ["capacity"]),
    ("Dependency management", "Visualize cross-team deps. API contracts early. Integration points in sprint 1 of dependent work.", "Planning", ["dependency"]),
    ("Change management", "ADKAR: Awareness, Desire, Knowledge, Ability, Reinforcement. Communicate why before what.", "Change", ["change", "adoption"]),
    ("Meeting hygiene", "No agenda → no meeting. Default 25/50 min. Async updates in doc before sync. Decision log.", "Productivity", ["meetings"]),
    ("Product discovery", "Dual track: discovery + delivery parallel. Prototype test ≤1 week. Evidence over opinions.", "Discovery", ["discovery", "validation"]),
    ("North Star metric", "One metric capturing core value. Input metrics vs output. Avoid vanity metrics.", "Metrics", ["north star", "kpi"]),
    ("Cost of delay", "CD3 = Cost of Delay / Duration. Prioritize by economic impact. WSJF in SAFe similar concept.", "Prioritization", ["cost of delay", "wsjf"]),
    ("Incident comms", "Status page, internal war room, postmortem blameless within 48h. Customer update cadence defined.", "Ops", ["incident", "comms"]),
    ("Vendor management", "SLA, SLO, review quarterly. Exit strategy in contract. POC before multi-year commit.", "Procurement", ["vendor", "sla"]),
    ("Remote team rituals", "Overlap hours documented. Async-first docs. Social time optional not mandatory.", "Remote", ["remote", "distributed"]),
    ("Onboarding checklist", "Day 1 access, week 1 buddy, month 1 first contribution. 30/60/90 day goals.", "HR", ["onboarding"]),
    ("Budget tracking", "Burn rate vs plan monthly. Forecast at completion. Scope change = change request.", "Finance", ["budget"]),
    ("Compliance projects", "Legal review gate. Audit trail. Data retention policy upfront.", "Compliance", ["gdpr", "compliance"]),
    ("AI team orchestration", "Route task to specialist agents not whole team. PM plans, specialists execute, evaluator validates. Artifact delivery in chat.", "AI Team", ["agents", "orchestration"]),
    ("Definition of Ready", "Story ready when: AC clear, deps resolved, estimated, testable, small enough for sprint.", "Quality", ["dor", "backlog"]),
    ("Sprint cancellation", "Only PO can cancel. Review completed work. Re-estimate remaining backlog.", "Scrum", ["cancel", "sprint"]),
])

# Continue with other agents - I'll create a compact multi-agent file using similar pattern
# Due to size, use build_all() function that imports submodules

ARCHITECT = _expand([
    ("Clean Architecture", "Entities → Use Cases → Interface Adapters → Frameworks. Dependency rule: inward only. Uncle Bob: business rules independent of UI, DB, frameworks.", "Patterns", ["clean", "layers", "uncle bob"]),
    ("Hexagonal Architecture", "Ports and Adapters. Domain core isolated. Primary ports (API) vs secondary (DB, messaging). Alistair Cockburn.", "Patterns", ["hexagonal", "ports"]),
    ("C4 Model", "Context → Container → Component → Code diagrams. Level 1 for stakeholders, level 2 for devs. Structurizr DSL or Mermaid.", "Diagrams", ["c4", "architecture"]),
    ("ADR format", "Title, Status, Context, Decision, Consequences. Immutable once accepted; supersede with new ADR. Store in docs/adr/.", "ADR", ["adr", "decisions"]),
    ("12-Factor App", "Codebase, dependencies, config, backing services, build/release/run, processes, port binding, concurrency, disposability, dev/prod parity, logs, admin processes.", "Cloud", ["12factor", "cloud native"]),
    ("Microservices patterns", "Database per service. Saga for distributed transactions. API Gateway, BFF per client. Circuit breaker, bulkhead, retry with backoff.", "Microservices", ["microservices", "saga"]),
    ("Event-driven architecture", "Event notification vs event-carried state transfer vs event sourcing. Kafka ordering per partition. Idempotent consumers.", "Events", ["kafka", "events"]),
    ("REST API design", "Resources nouns plural. HTTP verbs semantic. HATEOAS optional. Versioning: URL vs header. Pagination cursor-based for large sets.", "API", ["rest", "api"]),
    ("GraphQL vs REST", "GraphQL: single endpoint, client-driven queries, N+1 problem with DataLoader. REST: cache-friendly, simpler ops. Choose by client diversity.", "API", ["graphql", "rest"]),
    ("gRPC", "Protobuf contracts, HTTP/2, streaming. Internal service mesh. Not for browser direct (need grpc-web).", "API", ["grpc", "protobuf"]),
    ("Domain-Driven Design", "Ubiquitous language, bounded contexts, aggregates, entities, value objects. Context mapping: ACL, shared kernel, customer-supplier.", "DDD", ["ddd", "domain"]),
    ("CQRS", "Separate read/write models. Event sourcing optional. Good for complex domains, reporting scales. Eventual consistency challenges.", "Patterns", ["cqrs", "read model"]),
    ("CAP theorem", "Consistency, Availability, Partition tolerance — pick two under partition. PACELC extension. Design for partition tolerance in distributed systems.", "Distributed", ["cap", "distributed"]),
    ("Database selection", "OLTP: Postgres. Cache: Redis. Search: Elasticsearch. Time-series: TimescaleDB. Graph: Neo4j. Document: Mongo when schema flexible.", "Data", ["database", "postgres"]),
    ("Caching strategies", "Cache-aside, read-through, write-through, write-behind. TTL + invalidation on write. Stampede protection with lock.", "Performance", ["cache", "redis"]),
    ("API rate limiting", "Token bucket, sliding window. 429 + Retry-After header. Per-user vs per-IP vs per-API-key.", "Security", ["rate limit", "api"]),
    ("OAuth2/OIDC", "Authorization code + PKCE for SPAs. Client credentials for M2M. Scopes minimal. Refresh token rotation.", "Auth", ["oauth", "oidc"]),
    ("Zero Trust", "Never trust, always verify. mTLS service mesh. Identity-aware proxy. Least privilege IAM.", "Security", ["zero trust", "security"]),
    ("Threat modeling STRIDE", "Spoofing, Tampering, Repudiation, Information disclosure, DoS, Elevation. Data flow diagrams. Mitigate per threat.", "Security", ["stride", "threat"]),
    ("Scalability patterns", "Horizontal scale stateless services. Sharding by tenant/key. Read replicas. CDN static assets.", "Scale", ["scale", "sharding"]),
    ("Observability", "Logs, metrics, traces — three pillars. OpenTelemetry standard. SLO error budget. RED method: Rate, Errors, Duration.", "Ops", ["observability", "otel"]),
    ("SLI/SLO/SLA", "SLI = measured metric. SLO = internal target 99.9%. SLA = contract with penalties. Error budget = 1 - SLO.", "Reliability", ["slo", "sla"]),
    ("Disaster recovery", "RPO recovery point, RTO recovery time. Active-active vs active-passive. Regular DR drills.", "DR", ["disaster", "backup"]),
    ("Multi-tenancy", "Shared DB shared schema vs schema per tenant vs DB per tenant. Row-level security in Postgres.", "SaaS", ["multi-tenant", "saas"]),
    ("Feature flags architecture", "LaunchDarkly/Unleash pattern. Flag evaluation server-side. Kill switch for incidents.", "Delivery", ["feature flags"]),
    ("Monolith first", "Martin Fowler: don't start microservices until domain boundaries clear. Modular monolith stepping stone.", "Strategy", ["monolith", "modular"]),
    ("Strangler fig", "Gradually replace legacy by routing traffic to new system. Anti-corruption layer at boundary.", "Migration", ["strangler", "legacy"]),
    ("API versioning", "Breaking change policy. Deprecation sunset 6–12 months. Semantic versioning for packages.", "API", ["versioning"]),
    ("Idempotency", "Idempotency-Key header for POST. Store key → response 24h. Critical for payments and webhooks.", "API", ["idempotency"]),
    ("Webhook design", "Sign payload HMAC. Retry exponential backoff. Idempotent handler. Dead letter queue.", "Integration", ["webhook"]),
    ("Message queue patterns", "At-least-once vs exactly-once. Outbox pattern for DB + queue atomicity. Poison message handling.", "Messaging", ["queue", "outbox"]),
    ("Serverless fit", "Event-driven short tasks. Cold start mitigation. Stateless. Not for long-running or high-throughput steady load.", "Serverless", ["lambda", "serverless"]),
    ("Infrastructure as Code", "Terraform state remote locking. Modules reusable. Plan before apply. Drift detection.", "IaC", ["terraform", "iac"]),
    ("Kubernetes basics", "Pod, Deployment, Service, Ingress. Requests/limits. Liveness vs readiness probes. HPA on CPU/custom metrics.", "K8s", ["kubernetes", "k8s"]),
    ("Service mesh", "Istio/Linkerd: mTLS, traffic split canary, observability sidecar. Complexity cost — adopt when needed.", "Mesh", ["istio", "mesh"]),
    ("Data privacy by design", "Minimize collection. Encryption at rest and transit. DPIA for high-risk processing. Right to erasure flows.", "Privacy", ["gdpr", "privacy"]),
    ("Performance budgets", "API p95 <200ms target. Frontend LCP <2.5s. Set budgets in CI.", "Performance", ["budget", "latency"]),
    ("Architecture review checklist", "Scalability, security, operability, cost, team skills, time to market. Document trade-offs explicitly.", "Review", ["review", "tradeoff"]),
    ("System design interview pattern", "Requirements, estimates, API design, data model, high-level design, deep dive bottlenecks, trade-offs.", "Practice", ["system design"]),
])

BACKEND = _expand([
    ("FastAPI lifespan", "asynccontextmanager for startup/shutdown. Yield between init and cleanup. DB pool, Redis connect in lifespan.", "FastAPI", ["fastapi", "lifespan"]),
    ("Pydantic v2", "model_validate, model_dump. Field validators. ConfigDict. Performance vs v1 significant.", "Python", ["pydantic", "validation"]),
    ("Async SQLAlchemy 2.0", "async_sessionmaker, select() style 2.0. expire_on_commit=False for detached objects. Connection pool size tuning.", "Database", ["sqlalchemy", "async"]),
    ("PostgreSQL indexing", "B-tree default. GIN for JSONB/full-text. Partial indexes WHERE clause. EXPLAIN ANALYZE before production.", "PostgreSQL", ["postgres", "index"]),
    ("Redis patterns", "String cache, Hash objects, Sorted sets leaderboards, Pub/Sub not durable — use streams for persistence.", "Redis", ["redis", "cache"]),
    ("JWT best practices", "Short access token 15min. Refresh in httpOnly cookie. RS256 asymmetric. Validate aud, iss, exp.", "Auth", ["jwt", "auth"]),
    ("WebSocket FastAPI", "ConnectionManager pattern. Heartbeat ping. Auth on connect via query token. Broadcast to rooms.", "WebSocket", ["websocket", "realtime"]),
    ("Background tasks", "Celery + Redis/RabbitMQ for heavy work. ARQ async alternative. FastAPI BackgroundTasks only for light fire-and-forget.", "Tasks", ["celery", "queue"]),
    ("File upload", "Streaming upload, size limits, virus scan hook. S3 presigned URLs for large files. Content-Type validation.", "API", ["upload", "s3"]),
    ("Pagination", "Cursor-based: stable under inserts. Offset bad for large tables. Keyset pagination on indexed column.", "API", ["pagination", "cursor"]),
    ("Error handling", "Consistent JSON error schema. Never leak stack traces prod. Problem Details RFC 7807.", "API", ["errors", "rfc7807"]),
    ("Logging structlog", "JSON logs in prod. correlation_id per request. Context vars in async. Log levels: DEBUG dev, INFO prod.", "Logging", ["logging", "structlog"]),
    ("pytest async", "pytest-asyncio mode auto. Fixtures scope session for DB. Factory pattern test data.", "Testing", ["pytest", "async"]),
    ("Test containers", "Postgres Redis in Docker for integration tests. pytest-docker or testcontainers-python.", "Testing", ["integration", "docker"]),
    ("Migrations Alembic", "One migration per PR. Reversible downgrade. Never edit applied migration. Seed data separate.", "Database", ["alembic", "migration"]),
    ("Connection pooling", "pool_size = (2 * cpu_cores) + effective_spindle. pool_pre_ping=True. Timeout settings.", "Database", ["pool", "connection"]),
    ("N+1 query fix", "selectinload, joinedload SQLAlchemy. DataLoader pattern GraphQL. Monitor query count in tests.", "Performance", ["n+1", "orm"]),
    ("API security headers", "CORS explicit origins. CSP, X-Frame-Options, HSTS. Rate limit login endpoints.", "Security", ["security", "headers"]),
    ("Secrets management", "Never in code. env vars dev, Vault/AWS SM prod. Rotate keys quarterly.", "Security", ["secrets", "vault"]),
    ("Health checks", "/health live, /ready dependencies. Kubernetes uses both. Include version in response.", "Ops", ["health", "k8s"]),
    ("OpenAPI generation", "FastAPI auto docs /docs. Export openapi.json for clients. Speakeasy/fern codegen.", "API", ["openapi", "swagger"]),
    ("Dependency injection", "FastAPI Depends chain. Override in tests. Singleton vs request scope.", "FastAPI", ["di", "depends"]),
    ("Multitenancy RLS", "SET app.current_tenant. Row Level Security policies Postgres. Tenant_id on all tables.", "SaaS", ["rls", "tenant"]),
    ("Webhook receiver", "Verify signature. Process async via queue. Return 200 fast. Store raw payload audit.", "Integration", ["webhook"]),
    ("Stripe integration", "Idempotency-Key. Webhook signing secret. Customer portal. Test mode keys separate.", "Payments", ["stripe", "payments"]),
    ("Email async", "SendGrid/SES via queue. Template engine. Unsubscribe compliance. Retry transient failures.", "Email", ["email", "ses"]),
    ("Full-text search", "Postgres tsvector + GIN. Or Elasticsearch for fuzzy facets. Sync via CDC or queue.", "Search", ["search", "fts"]),
    ("CSV export streaming", "StreamingResponse generator. Don't load all rows memory. Content-Disposition attachment.", "Export", ["csv", "stream"]),
    ("PDF generation", "WeasyPrint HTML→PDF. ReportLab low-level. Puppeteer for complex layouts.", "Export", ["pdf"]),
    ("Time zones", "Store UTC in DB. Convert display user TZ. python zoneinfo. Never local time in DB.", "Datetime", ["timezone", "utc"]),
    ("Soft delete", "deleted_at column. Filter default queries. Hard delete GDPR erasure job.", "Database", ["soft delete"]),
    ("Optimistic locking", "version column increment on update. 409 Conflict if stale. UI retry prompt.", "Concurrency", ["locking"]),
    ("Distributed lock", "Redis Redlock with caution. DB advisory locks simpler. Lease timeout mandatory.", "Distributed", ["lock", "redis"]),
    ("GraphQL FastAPI", "Strawberry or Ariadne. DataLoader batch loads. Complexity limits depth/cost.", "GraphQL", ["strawberry"]),
    ("gRPC Python", "grpcio + protobuf. Async servicers. Health checking protocol.", "gRPC", ["grpc"]),
    ("Memory profiling", "tracemalloc, memray. Find leaks in long-running workers.", "Debug", ["memory", "profile"]),
    ("API mocking", "Prism, WireMock for contract tests. Mock external deps in CI.", "Testing", ["mock", "contract"]),
    ("Blue-green deploy", "Two environments switch traffic. DB migration compatibility forward-only.", "Deploy", ["blue-green"]),
    ("Feature flags backend", "Evaluate server-side. User targeting rules. Cache flag values 60s.", "Flags", ["feature flags"]),
    ("Rate limit Redis", "INCR + EXPIRE sliding window. slowapi for FastAPI integration.", "Security", ["rate limit"]),
    ("SQL injection prevention", "Always parameterized queries. ORM not raw string concat. Audit raw SQL usage.", "Security", ["sql injection"]),
])

FRONTEND = _expand([
    ("React 19", "Actions, use hook for promises. Server Components in Next.js. Concurrent rendering. Suspense boundaries for loading.", "React", ["react", "hooks"]),
    ("TypeScript strict", "strict true, noImplicitAny. Discriminated unions for state. satisfies operator. Type guards.", "TypeScript", ["typescript", "strict"]),
    ("State management", "useState local, Context rare, Zustand/Jotai medium, Redux Toolkit complex global. Server state: TanStack Query.", "State", ["zustand", "redux", "query"]),
    ("TanStack Query", "staleTime, cacheTime, invalidateQueries on mutation. Optimistic updates rollback on error. Prefetch on hover.", "Data fetching", ["react query", "cache"]),
    ("CSS modern layout", "Grid for 2D, Flexbox for 1D. container queries @container. clamp() fluid typography. gap not margin hacks.", "CSS", ["css", "grid", "flex"]),
    ("Tailwind patterns", "Design tokens in tailwind.config. @apply sparingly. Component classes with cva/clsx.", "Tailwind", ["tailwind", "utility"]),
    ("Accessibility WCAG 2.2", "Focus visible, skip links, aria-live regions, color contrast 4.5:1. Keyboard trap modals. Test with axe.", "a11y", ["wcag", "accessibility"]),
    ("Performance Core Web Vitals", "LCP largest contentful paint <2.5s. INP interaction <200ms. CLS layout shift <0.1. Lighthouse CI.", "Performance", ["lcp", "web vitals"]),
    ("Code splitting", "React.lazy + Suspense. Route-based split Vite/Webpack. Prefetch next route.", "Performance", ["split", "lazy"]),
    ("Vite config", "Proxy API dev. env variables VITE_ prefix. Build rollup options manualChunks.", "Tooling", ["vite", "build"]),
    ("Testing Library", "Query by role label. userEvent not fireEvent. Avoid implementation details. findBy for async.", "Testing", ["testing library", "jest"]),
    ("Playwright component", "Mount components isolated. Visual regression screenshots. Network mock.", "Testing", ["playwright", "e2e"]),
    ("Figma to code", "Auto layout → flex. Variants → props. Design tokens export JSON. Dev Mode inspect.", "Figma", ["figma", "design"]),
    ("Design tokens", "CSS variables or Style Dictionary. Semantic tokens color-bg-surface not color-gray-100.", "Design system", ["tokens", "design system"]),
    ("Storybook", "Stories per component state. Controls knobs. a11y addon. Visual test Chromatic.", "Storybook", ["storybook", "components"]),
    ("Form validation", "React Hook Form + Zod resolver. Server errors map to fields. Debounce async validate.", "Forms", ["forms", "zod"]),
    ("Internationalization", "i18next namespaces. Lazy load locales. RTL support logical properties.", "i18n", ["i18n", "locale"]),
    ("SSR Next.js App Router", "Server Components default. Client 'use client' boundary. Streaming HTML. Metadata API SEO.", "Next.js", ["nextjs", "ssr"]),
    ("SEO basics", "Semantic HTML, meta og tags, sitemap, robots.txt. JSON-LD structured data.", "SEO", ["seo", "meta"]),
    ("PWA", "manifest.json, service worker cache strategies. install prompt. offline fallback page.", "PWA", ["pwa", "service worker"]),
    ("WebSocket client", "Reconnect exponential backoff. Heartbeat. Message queue offline sync.", "Realtime", ["websocket"]),
    ("Error boundaries", "React error boundary per route section. Fallback UI report to Sentry.", "Errors", ["error boundary", "sentry"]),
    ("Sentry frontend", "Source maps upload CI. User context breadcrumbs. Performance transactions.", "Monitoring", ["sentry", "monitoring"]),
    ("Image optimization", "next/image or srcset. WebP/AVIF. lazy loading native. blur placeholder LQIP.", "Images", ["image", "webp"]),
    ("Animation", "CSS transitions prefer GPU transform/opacity. Framer Motion layout animations. prefers-reduced-motion.", "Animation", ["animation", "motion"]),
    ("Mobile first", "Touch targets 44px min. viewport meta. Safe area env(safe-area-inset).", "Mobile", ["mobile", "responsive"]),
    ("Dark mode", "prefers-color-scheme + manual toggle. CSS variables theme switch. No flash FOUC script.", "Theming", ["dark mode", "theme"]),
    ("Snow UI kit", "Background #F9F9FA, accent #4C98FD, indigo #ADADFB. Sidebar groups Work/Analytics/Planning. 12px radius.", "Design", ["snow ui", "dashboard"]),
    ("Table UX", "Sort, filter, pagination virtualized for 10k rows. Sticky header. Row selection bulk actions.", "UI", ["table", "data grid"]),
    ("Modal focus trap", "Focus first element open. Restore focus close. Escape dismiss. aria-modal true.", "UI", ["modal", "dialog"]),
    ("Command palette", "Ctrl+K fuzzy search actions. Keyboard navigation. Recent commands.", "UX", ["command palette", "kiosk"]),
    ("Toast notifications", "aria-live polite. Auto dismiss 5s. Action undo button. Stack limit 3.", "UX", ["toast", "notification"]),
    ("Skeleton loading", "Match layout shift prevent CLS. Shimmer optional. Prefer skeleton over spinner blocks.", "UX", ["skeleton", "loading"]),
    ("Infinite scroll vs pagination", "Pagination for SEO tables admin. Infinite social feeds. Load more button hybrid.", "UX", ["infinite scroll"]),
    ("Chart libraries", "Recharts simple. D3 custom. Chart.js canvas. Accessible data tables fallback.", "Charts", ["charts", "recharts"]),
    ("Monaco editor embed", "VS Code engine. Themes sync app. Language workers. Diff editor reviews.", "Editor", ["monaco", "code editor"]),
    ("Micro-frontends", "Module Federation Webpack. iframe isolation legacy. Single-spa orchestrator.", "Architecture", ["micro frontend"]),
    ("CORS frontend", "Credentials include cookies. Proxy dev Vite. Same-site cookies production.", "Security", ["cors", "cookies"]),
    ("XSS prevention", "Never dangerouslySetInnerHTML user content. DOMPurify sanitize. CSP script-src.", "Security", ["xss", "csp"]),
    ("Bundle analysis", "rollup-plugin-visualizer. Target <200kb initial JS gzip. Tree shake lodash-es.", "Performance", ["bundle", "size"]),
])

# Shorter packs for remaining agents - still ~30+ entries each
QA = _expand([
    ("Test pyramid", "Many unit, fewer integration, few E2E. Unit fast isolated. E2E brittle expensive.", "Strategy", ["pyramid", "testing"]),
    ("pytest fixtures", "conftest.py hierarchy. scope function/class/session. autouse sparingly. factory_boy data.", "pytest", ["pytest", "fixtures"]),
    ("Playwright best practices", "Page object model optional. getByRole locators. auto-wait built-in. trace on failure.", "E2E", ["playwright", "e2e"]),
    ("Visual regression", "Percy/Chromatic screenshot diff. Baseline review PR. Ignore anti-aliasing regions.", "Visual", ["visual", "regression"]),
    ("Contract testing", "Pact consumer-driven. Provider verification CI. Breaking change detection.", "Contract", ["pact", "api"]),
    ("Load testing k6", "Smoke load stress spike soak stages. Thresholds p95<500ms. Grafana cloud results.", "Load", ["k6", "performance"]),
    ("Test data management", "Synthetic data not prod copy. GDPR fake PII. Reset DB seed between tests.", "Data", ["test data"]),
    ("Flaky tests", "Quarantine flaky, fix within sprint. No retry without ticket. Root cause timing race.", "Quality", ["flaky"]),
    ("Accessibility testing", "axe-core automated. Manual screen reader NVDA. Focus order tab test.", "a11y", ["accessibility"]),
    ("Security testing OWASP", "ZAP scan CI. SQL injection payloads. Auth bypass attempts. Dependency audit.", "Security", ["owasp", "zap"]),
    ("Mobile testing", "Device farm BrowserStack. Touch gestures. Orientation change. Offline mode.", "Mobile", ["mobile", "testing"]),
    ("API testing", "Postman/Newman collections CI. Schema validation JSON Schema. Negative cases.", "API", ["api", "postman"]),
    ("Mutation testing", "mutmut Python. Kill rate metric. Surviving mutants improve tests.", "Advanced", ["mutation"]),
    ("Coverage goals", "80% line reasonable not gospel. Cover critical paths 100%. Mutation better than %.", "Metrics", ["coverage"]),
    ("Bug report template", "Steps reproduce, expected, actual, env, screenshots, logs, severity priority.", "Process", ["bug report"]),
    ("Exploratory testing", "Charter time-boxed. Session-based test management. Heuristics SFDPOT.", "Exploratory", ["exploratory"]),
    ("Regression suite", "Smoke <10min PR. Full nightly. Tag tests @smoke @regression.", "CI", ["regression"]),
    ("Test environments", "Dev staging prod parity. Feature branch preview URLs. Data refresh weekly.", "Env", ["staging"]),
    ("Performance budgets CI", "Lighthouse CI assert thresholds. Bundle size limit PR comment.", "CI", ["lighthouse"]),
    ("Shift left", "Tests in dev PR. Static analysis pre-commit. Design review testability.", "Culture", ["shift left"]),
    ("TDD cycle", "Red green refactor. Small steps. Not mandatory everywhere but useful algorithms.", "TDD", ["tdd"]),
    ("BDD Gherkin", "Given When Then scenarios. Cucumber bridge business-tech. Living documentation.", "BDD", ["gherkin", "cucumber"]),
    ("Snapshot testing", "Jest snapshots UI fragile. Review snapshot updates carefully. Prefer explicit asserts.", "Jest", ["snapshot"]),
    ("Parallel tests", "pytest-xdist workers. Playwright sharding. Isolate test DB per worker.", "Speed", ["parallel"]),
    ("CI pipeline tests", "Lint → unit → integration → E2E staging gate → deploy. Fail fast.", "CI", ["pipeline"]),
    ("Test ownership", "Feature team owns tests. QA coaches standards. No QA-only silo.", "Org", ["ownership"]),
    ("Release testing", "Release checklist sign-off. Rollback tested. Monitoring alerts post-deploy.", "Release", ["release"]),
    ("Chaos engineering", "Gremlin failure injection staging. Game days. MTTR improvement.", "Resilience", ["chaos"]),
    ("Accessibility WCAG audit", "Level AA target. Document exceptions. VPAT for enterprise.", "Compliance", ["wcag"]),
    ("Test documentation", "Test plan scope approach. Trace matrix requirements→tests.", "Docs", ["test plan"]),
])

REVIEWER = _expand([
    ("SOLID SRP", "Single Responsibility: one reason to change. Split god classes. Cohesion high coupling low.", "SOLID", ["srp", "solid"]),
    ("SOLID OCP", "Open closed: extend behavior without modifying. Strategy pattern plugins.", "SOLID", ["ocp"]),
    ("SOLID LSP", "Liskov: subtypes substitutable. No surprise exceptions in subclass.", "SOLID", ["lsp"]),
    ("SOLID ISP", "Interface segregation: small focused interfaces. Clients don't depend unused methods.", "SOLID", ["isp"]),
    ("SOLID DIP", "Depend on abstractions not concretions. Inject dependencies.", "SOLID", ["dip"]),
    ("Clean code naming", "Intention-revealing names. Pronounceable searchable. No abbreviations except standard.", "Clean Code", ["naming"]),
    ("Function size", "Small functions do one thing. Extract till readable. Max ~20 lines guideline.", "Clean Code", ["functions"]),
    ("Code smells", "Long method, large class, duplicate, feature envy, data clumps. Refactor catalog.", "Smells", ["smell", "refactor"]),
    ("Review checklist", "Correctness, tests, security, performance, readability, docs. Praise good code too.", "Process", ["code review"]),
    ("Constructive feedback", "Suggest not command. Ask questions. Link standards. Block only critical issues.", "Culture", ["feedback"]),
    ("Security review", "Input validation, authz checks, secrets, SQL injection, XSS, CSRF.", "Security", ["security review"]),
    ("Performance review", "N+1 queries, unnecessary loops, memory leaks, blocking IO in async.", "Performance", ["performance"]),
    ("API review", "RESTful conventions, error codes, pagination, versioning, breaking changes.", "API", ["api review"]),
    ("Test review", "Tests assert behavior not implementation. Edge cases covered. Readable names.", "Testing", ["test review"]),
    ("Architecture review", "Fit system design. No inappropriate coupling. Scalability considered.", "Architecture", ["architecture"]),
    ("Dependency review", "License compatibility. Maintenance activity. Security advisories npm audit.", "Dependencies", ["dependencies"]),
    ("Git diff best practice", "Small PRs <400 lines. One concern per PR. Meaningful commits.", "Git", ["pull request"]),
    ("Automated review tools", "Ruff/ESLint, SonarQube, CodeQL. Human review on top not replaced.", "Automation", ["lint", "sonar"]),
    ("Refactoring patterns", "Extract method, inline, rename, move. Martin Fowler catalog. Tests green.", "Refactoring", ["refactoring"]),
    ("Design patterns review", "Patterns used appropriately not over-engineered. GoF when clarity gained.", "Patterns", ["design patterns"]),
    ("Concurrency review", "Race conditions, deadlocks, lock ordering. Async await correctness.", "Concurrency", ["concurrency"]),
    ("Error handling review", "Don't swallow exceptions. Specific catch. User-friendly messages.", "Errors", ["exceptions"]),
    ("Logging review", "Appropriate levels. No sensitive data logs. Structured context.", "Logging", ["logging"]),
    ("Documentation review", "Public API documented. README updated. Breaking changes changelog.", "Docs", ["documentation"]),
    ("Accessibility code review", "Semantic HTML, alt text, keyboard, ARIA correct not overused.", "a11y", ["accessibility"]),
    ("Database migration review", "Reversible. Index concurrent if Postgres. Backfill strategy.", "Database", ["migration"]),
    ("Config review", "Defaults safe. Env documented. Feature flags off default.", "Config", ["configuration"]),
    ("Metrics review", "Useful not vanity. Cardinality explosion avoid labels.", "Observability", ["metrics"]),
    ("Review SLAs", "First response 4h. Complete 24h. Urgent security same day.", "Process", ["sla"]),
    ("Pair review mob", "Mob review complex changes. Knowledge spread. Faster consensus.", "Process", ["mob"]),
])

DOC_WRITER = _expand([
    ("Docs as Code", "Markdown in repo. PR review docs. CI link check. Version with code tags.", "Workflow", ["docs", "markdown"]),
    ("README structure", "What why how. Quick start 5 min. Configuration. Contributing. License.", "README", ["readme"]),
    ("OpenAPI 3.1", "paths, components schemas, examples. $ref reuse. Tags group endpoints.", "API docs", ["openapi"]),
    ("ADR writing", "Context problem. Decision made. Consequences positive negative. Status proposed accepted.", "ADR", ["adr"]),
    ("Technical writing style", "Active voice. Short sentences. Imperative headings. Define acronyms first use.", "Style", ["writing"]),
    ("Diátaxis framework", "Tutorials learning-oriented. How-to guides task-oriented. Reference info. Explanation understanding.", "Structure", ["diataxis"]),
    ("User documentation", "Persona based. Task titles not feature names. Screenshots annotated.", "User docs", ["user guide"]),
    ("Developer onboarding doc", "Day 1 setup. Architecture overview diagram. Common tasks cookbook.", "Onboarding", ["developer"]),
    ("Runbook ops", "Alert trigger. Investigation steps. Rollback procedure. Escalation contacts.", "Runbook", ["ops", "sre"]),
    ("Changelog Keep a Changelog", "Added Changed Fixed Removed. Semantic versioning link. Unreleased section.", "Changelog", ["changelog"]),
    ("API reference generation", "Redoc/Slate from OpenAPI. Code samples multi-language.", "API", ["reference"]),
    ("Diagrams in docs", "Mermaid in Markdown. C4 context container. Sequence for flows.", "Diagrams", ["mermaid"]),
    ("Localization docs", "Separate locale folders or Crowdin. Keep English source truth.", "i18n", ["localization"]),
    ("Search docs", "Algolia DocSearch. Static site MkDocs Material. Full-text index.", "Search", ["search"]),
    ("Versioned docs", "docs.site.com/v2/ latest redirect. Maintenance policy old versions.", "Versioning", ["version"]),
    ("Style guide Google", "Avoid jargon. Second person you. Present tense. Lists parallel structure.", "Style", ["google style"]),
    ("Accessibility docs", "Alt text images. Heading hierarchy. Code contrast in examples.", "a11y", ["accessibility"]),
    ("Security docs", "Responsible disclosure. Auth flows documented. No secrets in examples.", "Security", ["security"]),
    ("Tutorial writing", "Show outcome first. Step by step numbered. Test every step CI.", "Tutorial", ["tutorial"]),
    ("FAQ maintenance", "Real user questions. Update each release. Link deep docs.", "FAQ", ["faq"]),
    ("Glossary", "Domain terms defined. Link first use. PM and eng shared language.", "Glossary", ["glossary"]),
    ("Release notes user", "Benefits not internals. Screenshots new features. Known issues.", "Release", ["release notes"]),
    ("Compliance docs", "SOC2 policies. Data handling. Retention schedules.", "Compliance", ["compliance"]),
    ("Markdown lint", "markdownlint rules. Prettier format MD. Vale prose linter.", "Tooling", ["markdownlint"]),
    ("Static site generators", "MkDocs Material, Docusaurus, VitePress. Choose by ecosystem.", "Tools", ["mkdocs", "docusaurus"]),
    ("Documentation testing", "doctest code blocks. Link checker CI. OpenAPI contract valid.", "Testing", ["doctest"]),
    ("Information architecture", "Hierarchy max 3 clicks. Cross-links related. Breadcrumbs.", "IA", ["navigation"]),
    ("Video docs", "Short screencasts supplement not replace text. Transcripts SEO.", "Video", ["screencast"]),
    ("Feedback loop", "Was this helpful widget. Analytics popular pages. Quarterly audit.", "Improvement", ["feedback"]),
    ("Open source contributing", "CONTRIBUTING.md CODE_OF_CONDUCT. Issue templates. PR template.", "OSS", ["contributing"]),
])

DEVOPS = _expand([
    ("Docker multi-stage", "Build stage full SDK. Runtime slim alpine. Non-root USER. .dockerignore.", "Docker", ["docker", "container"]),
    ("Docker compose dev", "Services api db redis. Volumes persist data. Healthcheck depends_on condition.", "Compose", ["compose", "dev"]),
    ("Kubernetes deployment", "replicas 3 min prod. resources requests limits. rollingUpdate maxUnavailable 0.", "K8s", ["kubernetes", "deployment"]),
    ("Helm charts", "Values.yaml env specific. Templates helpers. Chart museum or OCI registry.", "Helm", ["helm"]),
    ("GitHub Actions", "Workflow trigger push PR. Matrix python versions. Cache pip. Secrets GH.", "CI", ["github actions", "ci"]),
    ("CI cache", "Dependency cache key hash lockfile. Docker layer cache buildkit.", "CI", ["cache"]),
    ("Terraform modules", "Remote state S3+dynamodb lock. Modules reusable. tfvars per env.", "Terraform", ["terraform", "iac"]),
    ("Ansible basics", "Idempotent tasks. Inventory groups. Vault encrypted secrets.", "Ansible", ["ansible"]),
    ("Prometheus metrics", "Counter only up. Gauge up down. Histogram buckets tune. alertmanager routes.", "Monitoring", ["prometheus"]),
    ("Grafana dashboards", "RED metrics dashboards. Variables environment. Annotations deploys.", "Grafana", ["grafana"]),
    ("Log aggregation", "Loki or ELK. JSON structured logs. retention policy cost.", "Logs", ["loki", "elk"]),
    ("OpenTelemetry", "Traces spans context propagate. Collector export Jaeger. Auto-instrument Python.", "Tracing", ["opentelemetry"]),
    ("Secrets K8s", "External Secrets Operator. Never ConfigMap secrets. Rotate automation.", "Secrets", ["secrets", "k8s"]),
    ("Ingress TLS", "cert-manager Let's Encrypt. nginx ingress controller. HSTS.", "Networking", ["ingress", "tls"]),
    ("Service mesh Istio", "VirtualService traffic split canary. mTLS strict mode.", "Mesh", ["istio"]),
    ("Canary deployment", "10% traffic new version. Metrics compare error rate. Auto rollback.", "Deploy", ["canary"]),
    ("Blue-green", "Switch load balancer. Database backward compatible migrations.", "Deploy", ["blue-green"]),
    ("Disaster recovery", "Backup Velero K8s. RPO 1h RTO 4h target. Runbook tested quarterly.", "DR", ["backup", "dr"]),
    ("Cost optimization", "Right-size pods VPA. Spot instances batch. Idle resource reports.", "FinOps", ["cost", "finops"]),
    ("Security scanning", "Trivy image scan CI fail critical. Snyk dependencies. Falco runtime.", "Security", ["trivy", "scan"]),
    ("SBOM", "Software bill materials CycloneDX. Supply chain compliance.", "Compliance", ["sbom"]),
    ("GitOps ArgoCD", "Repo desired state. Auto sync or manual promote. Diff preview.", "GitOps", ["argocd"]),
    ("Environment promotion", "dev auto deploy. staging on main. prod manual approval tag.", "Environments", ["promotion"]),
    ("Database ops", "Managed RDS. Backup PITR. Migration job K8s init container.", "Database", ["rds", "postgres"]),
    ("CDN CloudFront", "Static assets cache. Signed URLs private. Origin shield.", "CDN", ["cloudfront", "cdn"]),
    ("DNS Route53", "Health check failover. Low TTL cutover. Wildcard certs.", "DNS", ["route53"]),
    ("WAF", "OWASP ruleset. Rate limit geo block. AWS WAF Cloudflare.", "Security", ["waf"]),
    ("Incident response", "PagerDuty on-call. Runbook link alert. Postmortem template.", "Incidents", ["pagerduty", "oncall"]),
    ("SLO monitoring", "Error budget burn alert. Multi-window multi-burn-rate.", "SLO", ["slo", "error budget"]),
    ("Container security", "Read-only root filesystem. drop ALL capabilities. seccomp profile.", "Security", ["container hardening"]),
    ("Windows/Linux ops", "PowerShell DSC. systemd unit files. Log rotate.", "OS", ["systemd"]),
    ("Pipeline security", "OIDC cloud deploy no long-lived keys. Signed commits optional.", "CI security", ["oidc"]),
    ("Infrastructure testing", "terratest. Kitchen-Terraform. Policy OPA conftest.", "Testing", ["terratest"]),
    ("Capacity planning", "HPA CPU + custom metrics. Cluster autoscaler nodes. Forecast quarterly.", "Scale", ["hpa", "autoscaler"]),
])

CURSOR = _expand([
    ("Cursor Cloud Agents", "API launch agent on repo. Poll status. Apply diff or PR. Model selection.", "Cursor", ["cursor", "cloud agents"]),
    ("Cursor SDK Python", "cursor-sdk package local. API key auth. Streaming progress events.", "SDK", ["cursor sdk", "python"]),
    ("MCP protocol", "Model Context Protocol tools resources prompts. Stdio and SSE transport. JSON-RPC.", "MCP", ["mcp", "tools"]),
    ("Agentic coding loop", "Plan implement test iterate. Human review gate. Small commits.", "Workflow", ["agentic", "coding"]),
    ("Context window management", "Summarize old context. @file references. Ignore irrelevant paths .cursorignore.", "Context", ["context", "tokens"]),
    ("Prompt engineering code", "Specific file paths. Expected behavior tests. Constraints stack libs.", "Prompts", ["prompt"]),
    ("Code review agent", "Review diff only not whole repo. Security performance checklist.", "Review", ["code review", "ai"]),
    ("Refactoring agent", "Behavior preserving tests must pass. Stepwise not big bang.", "Refactoring", ["refactor"]),
    ("Test generation agent", "Cover edge cases. Mock externals. Readable test names.", "Testing", ["test generation"]),
    ("Documentation agent", "Update README when API changes. Docstrings public methods.", "Docs", ["documentation"]),
    ("Git workflow agent", "Feature branch. Conventional commits. PR description template.", "Git", ["git", "pr"]),
    ("Monorepo navigation", "Turborepo nx boundaries. Change impact analysis.", "Monorepo", ["monorepo"]),
    ("Dependency updates", "Renovate bot config. Pin major review minor auto.", "Dependencies", ["renovate"]),
    ("Security fix agent", "CVE priority score. Minimal patch version bump.", "Security", ["cve", "patch"]),
    ("API integration agent", "Read OpenAPI spec. Generate client. Error handling retries.", "Integration", ["openapi"]),
    ("Frontend agent", "Component from Figma description. Storybook story add.", "Frontend", ["react", "component"]),
    ("Backend agent", "Endpoint schema first. Migration script. Integration test.", "Backend", ["fastapi", "api"]),
    ("DevOps agent", "Dockerfile optimize. CI workflow fix. K8s manifest lint.", "DevOps", ["docker", "ci"]),
    ("Debugging agent", "Reproduce steps. Log analysis. Bisect commit range.", "Debug", ["debugging"]),
    ("Performance agent", "Profile hotspot. Query explain. Bundle analyze.", "Performance", ["profiling"]),
    ("Migration agent", "Framework upgrade guide. Codemods run. Deprecated API replace.", "Migration", ["upgrade"]),
    ("Composer model", "Multi-file edits coherent. Instruction clarity critical.", "Cursor", ["composer"]),
    ("Rules cursor", ".cursor/rules project conventions. Always apply stack patterns.", "Config", ["cursor rules"]),
    ("Background agents", "Long tasks async notify complete. Don't block interactive.", "Async", ["background"]),
    ("PR automation", "Fix CI failures push commits. Respond review comments.", "Automation", ["pull request"]),
    ("Repo sync", "Fetch rebase main before feature. Conflict resolution strategy.", "Git", ["sync", "rebase"]),
    ("Multi-model routing", "Strong model architecture. Fast model boilerplate.", "Models", ["routing"]),
    ("Cost control", "Token budget per task. Cache repeated context.", "Cost", ["tokens", "budget"]),
    ("Evaluation coding", "HumanEval style benchmarks internal tasks. Regression suite prompts.", "Eval", ["evaluation"]),
    ("Sandbox execution", "Docker isolate run user code. Network restrict. Timeout kill.", "Security", ["sandbox"]),
])

PRESENTER = _expand([
    ("Pitch deck structure", "Problem solution market product traction team ask. 10-15 slides seed stage.", "Pitch", ["pitch", "startup"]),
    ("Story arc", "Hook first 30 sec. Conflict tension. Resolution demo. CTA clear ask.", "Storytelling", ["story", "narrative"]),
    ("One idea per slide", "6 words headline max. Visual support not duplicate speaker notes.", "Design", ["slides", "design"]),
    ("Data visualization slides", "One chart per slide. Source footnote. Highlight key data point color.", "Data", ["charts", "presentation"]),
    ("Investor pitch timing", "3 min teaser. 10 min full. Demo live not video if possible.", "Investor", ["investor", "demo"]),
    ("Tech talk structure", "Who am I. Problem space. Approach. Live demo. Lessons learned. Q&A.", "Tech talk", ["conference", "talk"]),
    ("Slide typography", "Max 2 fonts. Size hierarchy 44/32/24. Contrast background text.", "Typography", ["fonts", "design"]),
    ("Color psychology", "Blue trust tech. Green growth. Red urgency sparingly. Brand consistency.", "Color", ["color", "brand"]),
    ("Animation restraint", "Reveal bullet by bullet max. No distracting transitions. Export PDF static fallback.", "Animation", ["animation"]),
    ("Speaker notes", "Notes pane not on slide. Timing cues. Backup answers FAQ.", "Notes", ["speaker notes"]),
    ("Demo day tips", "Backup video if live fails. Rehearse 5x. Clicker tested. Water nearby.", "Demo", ["demo day"]),
    ("Executive summary slide", "Single slide CEO decision. Metrics ROI timeline risk.", "Executive", ["executive", "summary"]),
    ("Product roadmap slide", "Now next later horizon. Themes not feature laundry list.", "Roadmap", ["roadmap", "product"]),
    ("Team slide", "Photos names roles 1 line cred. Advisors logos permission.", "Team", ["team", "about"]),
    ("Competition slide", "2x2 matrix differentiation. Honest not trash competitors.", "Market", ["competition", "matrix"]),
    ("Financial slide", "Key metrics ARR burn runway. Assumptions footnote.", "Finance", ["financials", "metrics"]),
    ("Ask slide", "Specific amount use of funds milestones. Contact info.", "Fundraising", ["ask", "funding"]),
    ("Appendix slides", "Detailed data backup. Not presented live available Q&A.", "Appendix", ["appendix"]),
    ("Remote presentation", "Camera eye level. Share slide not whole screen. Poll engagement.", "Remote", ["zoom", "remote"]),
    ("Accessibility slides", "Alt text images export. Readable by screen reader PDF tags.", "a11y", ["accessibility"]),
    ("PPTX generation", "python-pptx Title Content layouts. Brand master slide template.", "Technical", ["pptx", "python"]),
    ("HTML slides reveal.js", "Markdown source. Speaker notes plugin. PDF print CSS.", "HTML", ["reveal.js", "html"]),
    ("Google Slides API", "Automate create slides programmatically. Template copy.", "Automation", ["google slides"]),
    ("PowerPoint master", "Slide master consistent footer logo. Theme colors embedded.", "PowerPoint", ["powerpoint", "template"]),
    ("Chart in slides", "Editable data not screenshot. Link Excel optional.", "Charts", ["excel", "chart"]),
    ("Video embed", "Short <30s. Autoplay off present mode. Compress size.", "Media", ["video"]),
    ("Handout vs slides", "Dense handout separate. Slides minimal verbal complement.", "Materials", ["handout"]),
    ("Q&A preparation", "Anticipate 10 hard questions. Bridge phrases. Honest I will follow up.", "Q&A", ["questions"]),
    ("Cultural adaptation", "Localize examples metrics currency. Humor careful.", "Global", ["localization"]),
    ("Post presentation", "Send deck PDF 24h. Survey feedback. CRM follow-up.", "Follow-up", ["follow up"]),
])

MODELER = _expand([
    ("Three.js scene graph", "Scene Camera Renderer. Mesh Geometry Material. Group hierarchy transforms.", "Three.js", ["three.js", "webgl"]),
    ("PBR materials", "Metalness roughness workflow. HDRI environment map. Tone mapping ACES.", "Materials", ["pbr", "materials"]),
    ("glTF 2.0", "Standard exchange format. Binary .glb preferred. Extensions KHR_draco_mesh_compression.", "glTF", ["gltf", "glb"]),
    ("Blender to glTF", "Apply transforms export. Scale 1 unit = 1 meter. Bake animations.", "Blade", ["blender", "export"]),
    ("Lighting three point", "Key fill rim. Shadow map bias. Hemisphere ambient.", "Lighting", ["lighting", "3d"]),
    ("Camera controls", "OrbitControls damping. Fit camera box3 setFromObject. FOV perspective.", "Camera", ["orbit", "camera"]),
    ("Performance WebGL", "InstancedMesh many objects. LOD levels. Frustum culling automatic. Texture size power 2.", "Performance", ["optimization", "webgl"]),
    ("Draco compression", "Geometry compression smaller GLB. Loader DRACOLoader path decoder.", "Compression", ["draco"]),
    ("Animation mixers", "AnimationMixer clipAction. Crossfade clips. Skeleton skinned mesh.", "Animation", ["animation", "rig"]),
    ("Raycasting pick", "Raycaster mouse normalized device coords intersect objects.", "Interaction", ["raycast", "pick"]),
    ("Postprocessing", "EffectComposer bloom SSAO optional cost. Render pass base.", "Effects", ["postprocessing"]),
    ("Shader basics", "Vertex shader positions. Fragment shader colors. Uniforms time resolution.", "Shaders", ["glsl", "shader"]),
    ("Procedural geometry", "BufferGeometry custom attributes. Parametric shapes. Merge geometries caution.", "Geometry", ["geometry", "procedural"]),
    ("UV mapping", "Unwrap Blender smart UV. Texture repeat wrap modes.", "UV", ["uv", "texture"]),
    ("Normal maps", "Tangent space normals detail without geometry. Bitangent compute.", "Normals", ["normal map"]),
    ("Skybox environment", "CubeTexture or equirectangular HDR. scene.background environment.", "Environment", ["skybox", "hdr"]),
    ("Physics cannon-es", "Rigid bodies colliders. Performance limit bodies. Sleep inactive.", "Physics", ["physics", "cannon"]),
    ("WebXR VR", "VRButton enter XR session. Controller models hand tracking optional.", "XR", ["webxr", "vr"]),
    ("React Three Fiber", "Declarative Three.js. useFrame hook. Drei helpers Html OrbitControls.", "R3F", ["react three fiber", "r3f"]),
    ("Model optimization", "Decimate modifier Blender. Texture atlas combine. Remove hidden faces.", "Optimization", ["optimize", "mesh"]),
    ("Asset pipeline", "glTF Transform CLI optimize. Validate with gltf-validator.", "Pipeline", ["pipeline", "assets"]),
    ("Level of detail", "LOD objects distance switch. Impostors billboards far.", "LOD", ["lod"]),
    ("Scene export web", "GLTFExporter three.js. Include lights cameras optional.", "Export", ["export", "gltf"]),
    ("Material variants", "KHR_materials_variants switch materials SKU product configurator.", "Variants", ["variants", "product"]),
    ("CAD to web", "Convert STEP IFC pipeline. Simplify mesh limit triangles web.", "CAD", ["cad", "conversion"]),
    ("Point clouds", "Points material size attenuation. LAZ load decimate.", "Point cloud", ["lidar", "points"]),
    ("Nav mesh AI", "Recast navigation walkable surfaces agent path 3D games.", "Navigation", ["navmesh", "ai"]),
    ("Collaborative 3D", "Multiplayer sync transforms websocket. CRDT optional.", "Multiplayer", ["multiplayer", "sync"]),
    ("Mobile WebGL", "Reduce draw calls. Power preference high performance. Touch orbit.", "Mobile", ["mobile", "webgl"]),
    ("Accessibility 3D", "Text alternatives describe scene. Keyboard focus optional 2D fallback.", "a11y", ["accessibility", "3d"]),
])

EVALUATOR = _expand([
    ("Quality rubric", "Criteria weighted scores 1-10. Clarity completeness correctness UX. Document weights.", "Rubric", ["rubric", "quality"]),
    ("Definition of Done audit", "Checklist automated where possible. Human judgment UX copy.", "DoD", ["definition of done"]),
    ("Skill matrix", "Agent capabilities vs task requirements gap analysis.", "Skills", ["skills", "matrix"]),
    ("Peer evaluation", "Cross-agent review frontend evaluates backend API usability.", "Peer", ["peer review"]),
    ("User satisfaction proxy", "Task completion time revision count error rate.", "Metrics", ["satisfaction"]),
    ("Artifact completeness", "Required files present preview works download succeeds.", "Artifacts", ["artifact", "complete"]),
    ("Presentation quality", "Structure narrative visuals timing checklist.", "Presentation", ["presentation", "evaluate"]),
    ("Code quality gates", "Lint pass tests pass coverage threshold security scan.", "Code", ["code quality"]),
    ("Documentation quality", "Accurate up to date examples run spell check.", "Docs", ["documentation"]),
    ("Accessibility audit score", "WCAG violations count severity.", "a11y", ["accessibility", "audit"]),
    ("Performance benchmark", "Latency throughput vs SLA. Regression compare baseline.", "Performance", ["benchmark"]),
    ("Security posture score", "OWASP checklist dependency CVE count secrets scan.", "Security", ["security score"]),
    ("Revision tracking", "Count iterations to acceptance. High revisions process issue.", "Process", ["revision"]),
    ("Feedback synthesis", "Aggregate evaluator notes actionable summary owner.", "Feedback", ["synthesis"]),
    ("Continuous improvement", "Retro metrics trends improve rubric quarterly.", "Improvement", ["kaizen"]),
    ("Bias detection", "Template repeated outputs lack task specificity flag.", "AI quality", ["bias", "template"]),
    ("Hallucination check", "Facts verifiable sources cited. Code runs.", "AI quality", ["hallucination"]),
    ("Comparative evaluation", "A vs B blind compare winner criteria.", "Compare", ["compare", "ab test"]),
    ("Stakeholder sign-off", "Explicit approve reject rework decision logged.", "Approval", ["sign-off"]),
    ("Learning from eval", "Failed criteria → training data pack update.", "Learning", ["learning loop"]),
    ("Risk scoring output", "Low medium high release risk recommendation.", "Risk", ["risk", "release"]),
    ("Compliance check", "License headers GDPR data handling checklist.", "Compliance", ["compliance"]),
    ("UX heuristic eval", "Nielsen 10 heuristics severity rating.", "UX", ["heuristic", "ux"]),
    ("Test adequacy", "Requirements traced tests critical paths covered.", "Testing", ["test coverage"]),
    ("Evaluation report template", "Summary scores evidence recommendations priority.", "Report", ["report"]),
])

SECURITY = _expand([
    ("OWASP Top 10 2021", "A01 Broken Access Control. A02 Cryptographic Failures. A03 Injection. A04 Insecure Design. A05 Misconfiguration.", "OWASP", ["owasp", "top 10"]),
    ("SQL injection", "Parameterized queries ORM. WAF secondary. Input validation allowlist.", "Injection", ["sql injection"]),
    ("XSS types", "Stored reflected DOM. CSP script-src. sanitize HTML DOMPurify.", "XSS", ["xss", "cross-site"]),
    ("CSRF protection", "SameSite cookies Strict. CSRF token double submit. Verify Origin header.", "CSRF", ["csrf"]),
    ("Authentication best practices", "MFA TOTP WebAuthn. Password hash Argon2 bcrypt. Rate limit login.", "Auth", ["authentication", "mfa"]),
    ("Authorization RBAC ABAC", "Least privilege. Policy engine OPA. Resource-level checks not only route.", "Authz", ["authorization", "rbac"]),
    ("Secrets management", "Vault AWS SM. Never git secrets. Pre-commit detect-secrets gitleaks.", "Secrets", ["secrets", "vault"]),
    ("TLS configuration", "TLS 1.2+ only. Strong ciphers. HSTS preload. Cert rotation automation.", "TLS", ["tls", "https"]),
    ("Security headers", "CSP X-Frame-Options X-Content-Type-Options Referrer-Policy Permissions-Policy.", "Headers", ["security headers"]),
    ("Dependency scanning", "npm audit pip audit Snyk. SBOM CycloneDX. Pin versions lockfile.", "Supply chain", ["dependencies", "sbom"]),
    ("SAST", "Semgrep CodeQL static analysis CI. Custom rules org patterns.", "SAST", ["sast", "semgrep"]),
    ("DAST", "OWASP ZAP baseline scan staging. Authenticated scan config.", "DAST", ["dast", "zap"]),
    ("Penetration testing", "Scope rules of engagement. Report severity CVSS remediate SLA.", "Pentest", ["pentest"]),
    ("Incident response security", "Contain eradicate recover. Preserve evidence. Notify legal 72h GDPR.", "Incident", ["incident", "breach"]),
    ("Zero day response", "Monitor advisories. Virtual patch WAF. Emergency change process.", "Vulnerability", ["zero day", "cve"]),
    ("Logging security", "Audit log tamper evident. Who what when where. No passwords logs.", "Logging", ["audit log"]),
    ("PII handling", "Minimize collect. Encrypt rest transit. Retention delete schedule. DSR process.", "Privacy", ["pii", "gdpr"]),
    ("Threat modeling STRIDE", "Data flow diagram trust boundaries. Mitigate each threat per element.", "Threat model", ["stride", "threat"]),
    ("Secure SDLC", "Security requirements design review code review test deploy gates.", "SDLC", ["secure sdlc"]),
    ("API security", "OAuth scopes minimal. Rate limit. Input schema validation. No verbose errors.", "API", ["api security"]),
    ("Cloud security shared model", "AWS shared responsibility. IAM policies least privilege. GuardDuty.", "Cloud", ["aws", "cloud security"]),
    ("Container security", "Non-root read-only rootfs scan Trivy. Network policy default deny.", "Container", ["docker security"]),
    ("K8s security", "RBAC namespace isolation Pod Security Standards restricted. Secrets encrypted etcd.", "K8s", ["kubernetes security"]),
    ("Network segmentation", "VPC subnets private public. Security groups minimal ports.", "Network", ["network", "firewall"]),
    ("WAF rules", "OWASP CRS managed rules. Geo block optional. Bot management.", "WAF", ["waf"]),
    ("Email security", "SPF DKIM DMARC. Phishing simulation training.", "Email", ["phishing", "email"]),
    ("Social engineering", "Verify wire transfer callbacks. Security awareness training.", "Awareness", ["social engineering"]),
    ("Cryptography basics", "AES-256-GCM symmetric. RSA-2048+ or ECDSA P-256 asymmetric. Never roll own crypto.", "Crypto", ["encryption", "crypto"]),
    ("Key rotation", "Annual keys quarterly tokens. Dual sign overlap period.", "Keys", ["rotation", "keys"]),
    ("Security champions", "Dev team embed security liaison. Office hours review help.", "Culture", ["security champions"]),
    ("Compliance frameworks", "SOC2 ISO27001 HIPAA mapping controls evidence.", "Compliance", ["soc2", "iso27001"]),
    ("Red team blue team", "Simulated attack exercises. Improve detection response.", "Exercise", ["red team"]),
    ("Bug bounty", "Scope defined safe harbor. Triage SLA payout tiers.", "Bounty", ["bug bounty", "hackerone"]),
    ("AI security", "Prompt injection mitigate. Output filter PII. Tool permission sandbox.", "AI", ["prompt injection", "llm security"]),
    ("Data classification", "Public internal confidential restricted. Handling rules per class.", "Data", ["classification"]),
    ("Backup encryption", "Encrypted backups separate keys. Test restore quarterly.", "Backup", ["backup", "encryption"]),
    ("Secure deletion", "Crypto erase keys. Overwrite standards NIST 800-88.", "Deletion", ["data destruction"]),
    ("Vendor security review", "Questionnaire SOC2 pen test results. Data processing agreement.", "Vendor", ["third party"]),
    ("Physical security", "Badge access logs. Clean desk policy. Secure disposal hardware.", "Physical", ["physical security"]),
])

ALL_PACKS: dict[str, list] = {
    "pm": PM,
    "architect": ARCHITECT,
    "backend": BACKEND,
    "frontend": FRONTEND,
    "qa": QA,
    "reviewer": REVIEWER,
    "doc_writer": DOC_WRITER,
    "devops": DEVOPS,
    "cursor": CURSOR,
    "presenter": PRESENTER,
    "modeler": MODELER,
    "evaluator": EVALUATOR,
    "security": SECURITY,
}


def get_all_packs() -> dict[str, list]:
    return ALL_PACKS


def pack_stats() -> dict:
    return {aid: len(entries) for aid, entries in ALL_PACKS.items()}
